### ISSUE TITLE
errors endpoint doesn't validate poolId properly

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/smash#82]
According to the API docs, if you call the /v1/errors endpoint with an invalid poolId, it should return a 400 error.

![Screenshot from 2020-09-18 13-27-58](https://user-images.githubusercontent.com/245918/93642377-dae29a00-f9b2-11ea-8406-f28d9fa3996f.png)

It appears to not be validating the poolId at all and instead returning a 200 response with empty errors list.

```
$ curl -X GET -v https://smash.cardano-testnet.iohkdev.io/api/v1/errors\?poolId\=bogus_pool_id                                           
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 18.157.202.11:443...
* TCP_NODELAY set
* Connected to smash.cardano-testnet.iohkdev.io (18.157.202.11) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=smash.cardano-testnet.iohkdev.io
*  start date: Jul 29 01:11:05 2020 GMT
*  expire date: Oct 27 01:11:05 2020 GMT
*  subjectAltName: host "smash.cardano-testnet.iohkdev.io" matched cert's "smash.cardano-testnet.iohkdev.io"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x558e767e7db0)
> GET /api/v1/errors?poolId=bogus_pool_id HTTP/2
> Host: smash.cardano-testnet.iohkdev.io
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx
< date: Fri, 18 Sep 2020 20:28:56 GMT
< content-type: application/json;charset=utf-8
< vary: Accept-Encoding
< vary: Origin
< access-control-allow-methods: GET, PATCH, OPTIONS
< access-control-allow-headers: User-Agent,X-Requested-With,Content-Type
< 
* Connection #0 to host smash.cardano-testnet.iohkdev.io left intact
[]%
```

**Comment by ksaric** [comment]
@AndrewWestberg Indeed, that is true for most of the responses. Will be improved soon, will notify here.

**Comment by ksaric** [comment]
Implemented in https://github.com/input-output-hk/smash/pull/122

**Comment by AndrewWestberg** [comment]
Now I'm still seeing a 404 error correctly for a bogus pool id, but I would expect a 200 when I submit with a valid pool id even if it has no errors. I would expect `[]` response for this query on the testnet. 

```
$ curl -X GET -v https://smash.cardano-testnet.iohkdev.io/api/v1/errors\?poolId\=3299895e62b13de5a5a52f4bb5726db5fb38928c8d2c21ff8d78517d
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 18.157.202.11:443...
* TCP_NODELAY set
* Connected to smash.cardano-testnet.iohkdev.io (18.157.202.11) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=smash.cardano-testnet.iohkdev.io
*  start date: Sep 28 15:13:13 2020 GMT
*  expire date: Dec 27 15:13:13 2020 GMT
*  subjectAltName: host "smash.cardano-testnet.iohkdev.io" matched cert's "smash.cardano-testnet.iohkdev.io"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55942543ddb0)
> GET /api/v1/errors?poolId=3299895e62b13de5a5a52f4bb5726db5fb38928c8d2c21ff8d78517d HTTP/2
> Host: smash.cardano-testnet.iohkdev.io
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404 
< server: nginx
< date: Sun, 22 Nov 2020 18:56:15 GMT
< vary: Origin
< access-control-allow-methods: GET, PATCH, OPTIONS
< access-control-allow-headers: User-Agent,X-Requested-With,Content-Type
< 
* Connection #0 to host smash.cardano-testnet.iohkdev.io left intact
```

**Comment by ksaric** [comment]
Yes, the new implemented features will be in the new release, probably next week.
Currently, you can try with this - `curl -X GET -v https://smash.cardano-testnet.iohkdev.io/api/v1/errors/3299895e62b13de5a5a52f4bb5726db5fb38928c8d2c21ff8d78517d` which is the correct format, but requires the admin authorization for it. It shouldn't, but it could be that the NGINX auth was left in. Will sort it out with DevOps.

**Comment by ksaric** [comment]
@AndrewWestberg Try it now, it should be fixed.

**Comment by AndrewWestberg** [comment]
@ksaric Still broken. Now we're back to the original issue. I'm getting a 200 response for a bogus pool entry. The docs state that it should return a 400.

**Comment by ksaric** [comment]
> @ksaric Still broken. Now we're back to the original issue. I'm getting a 200 response for a bogus pool entry. The docs state that it should return a 400.

That is because that fix is still not released. As I mentioned, it will be in the next release, probably called `1.3.0`.

**Comment by ksaric** [comment]
You can try this with the newest release - https://github.com/input-output-hk/smash/releases/tag/1.3.0

**Comment by AndrewWestberg** [comment]
This still doesn't work right. If I send in a pool id that doesn't exist, I'm getting a 200.

**Comment by ksaric** [comment]
@AndrewWestberg All the best in the new year. Please provide the example, since `curl -X GET -v https://smash.cardano-testnet.iohkdev.io/api/v1/errors?poolId=bogus_pool_id` returns 404.

**Comment by AndrewWestberg** [comment]
@ksaric 

Valid PoolId: 3299895e62b13de5a5a52f4bb5726db5fb38928c8d2c21ff8d78517d
Expected: 200 result with `[]` showing no metadata errors
Actual: 404
Command: `curl -X GET -v https://smash.cardano-testnet.iohkdev.io/api/v1/errors\?poolId\=3299895e62b13de5a5a52f4bb5726db5fb38928c8d2c21ff8d78517d`

If I hit this URL, I get the proper 200+`[]` result for this request:
curl -X GET -v https://smash.cardano-testnet.iohkdev.io/api/v1/errors/3299895e62b13de5a5a52f4bb5726db5fb38928c8d2c21ff8d78517d

Another example...
Invalid poolId: f299895e62b13de5a5a52f4bb5726db5fb38928c8d2c21ff8d78517d
Expected: 404
Actual: 404
Command: `curl -X GET -v https://smash.cardano-testnet.iohkdev.io/api/v1/errors?poolId=f299895e62b13de5a5a52f4bb5726db5fb38928c8d2c21ff8d78517d`

If I hit this URL, I get the INCORRECT result of 200+`[]` for this request since the pool doesn't exist on the chain:
`curl -X GET -v https://smash.cardano-testnet.iohkdev.io/api/v1/errors/f299895e62b13de5a5a52f4bb5726db5fb38928c8d2c21ff8d78517d`

**Comment by ksaric** [comment]
The first example is a matter of format. The second case is the example of a correct format.

The second example is somewhat more debatable. While it is true that the SMASH server now validates the format of the pool id (which is the name/cause of the opened issue), the existence of the actual pool id is not checked and it always returns an empty list for a pool id which doesn't exist. This could be fixed in the near future (I might fix it soon), but I don't think the actual issue is that critical.

In any case, the validation now works and you can check that by providing an invalid pool id.

**Comment by AndrewWestberg** [comment]
@ksaric Having a way to validate if a pool_id actually exists on-chain is my main use case. The only other way to do this is with a ledger-state dump which is very resource intensive and time consuming. For JorManager, I need to know whether a pool_id exists in order to know whether a change should be a pool registration, or a re-registration. On mainnet, there are other options like adapools api, etc. On the testnets and the devnets, there are no options other than ledger-state. It would be nice if smash could have a simple api to check if a pool has been registered on the chain (which I thought this api would do for me).

**Comment by ksaric** [comment]
@AndrewWestberg I see. That is another use case and a pretty valid one at that. I will add that check soon and inform you of it.

**Comment by ksaric** [comment]
Implemented and released in https://github.com/input-output-hk/smash/releases/tag/v1.4.0, will be deployed soon.

**Comment by AndrewWestberg** [comment]
@ksaric When does the /exists endpoint go live? Is 1.4.0 deployed to mainnet or testnet yet? It doesn't appear to be live.

**Comment by ksaric** [comment]
@AndrewWestberg The endpoint exists in the deployed version, will check it and get back to you.

**Comment by jbgi** [comment]
@AndrewWestberg the endpoint has now been exposed, should now work.
